<br /><br />
<div id="view-content">
	<p>View script for controller <b>Clients</b> and script/action name <b>index</b></p>
</div>

<p>Liste des <b>Clients</b>
    </div>
     <a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'ajouter')); ?>">Ajouter clients</a> 
    <table border="6">
        <tr>

            <th>Numéro du client </th>
        
             <th>Nom</th>
     
            <th>Prenom</th>
     
            <th>Adresse</th>
     
            <th> Code postale</th>
     
            <th> Téléphone</th>
            
        </tr>
        
    </html>
     
        <?php
        foreach ($this->Lesclients as $unclient) {
            ?>
            <tr>
                <td><?php echo $unclient->NUM_CLI;?></td></td>
     
                <td><?php echo $unclient->NOM_CLI;?></td></td>
                
                <td><?php echo $unclient->PRENOM_CLI;?></td></td>
     
                <td><?php echo $unclient->ADRESSE_CLI;?></td></td>
     
                <td><?php echo $unclient->CODEVILLE_CLI;?></td></td>
     
                <td><?php echo $unclient->TEL_CLI;?></td></td>
     
   
                
                <td><a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'modifier',  'NUM_CLI'=>$unclient->NUM_CLI)); ?>">Modifier</a></td>
                
                <td><a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'supprimer', 'NUM_CLI'=>$unclient->NUM_CLI)); ?>">Supprimer</a></td>
                
            </tr>
            <?php
        }
        ?>
    </table>