
<p> Etes vous sur de vouloir supprimer ce client: 
    '<?php echo $this->lesclients['NOM_CLI']." ".$this->lesclients['PRENOM_CLI']." (identifiant:" .$this->lesclients['NUM_CLI'].")"; ?>'?
</p>

<form action="<?php echo $this->url(array('controller' =>'clients', 'action'=>'supprimer')); ?>" method="post">
    <div>
        <input type="hidden" name="NUM_CLI" value="<?php echo $this->numcli; ?>" />
        <input type="submit" name="supprimer" value="oui"/>
        <input type="submit" name="supprimer" value="non"/>
    </div>
</form>
