<div id="welcome">
    <h1>Gestionaire de location</h1>

    <h3>Projet ZF1-FromScratch</h3>

    <h2>
        Gestion des locations 
    
    
   
        
    </h2>
    <table>
         
        
            <tr>
                <td><a href="<?php echo $this->url(array('controller' => 'clients', 'action' => 'index')); ?>"><button>Client</button></a></td>
       <td><a href="<?php echo $this->url(array('controller' => 'demandes', 'action' => 'index')); ?>"><button>Demandes</button></a></td>
       <td><a href="<?php echo $this->url(array('controller' => 'locataires', 'action' => 'index'));?>"><button>Locataires</button></a></td>
       <td><a href="<?php echo $this->url(array('controller' => 'appartements', 'action' => 'index')); ?>"><button>Appartements</button></a></td>
       <td><a href="<?php echo $this->url(array('controller' => 'proprietaires', 'action' => 'index')); ?>"><button>Propriétaire</button></a></td>
       <td><a href="<?php echo $this->url(array('controller' => 'visiter', 'action' => 'index')); ?>"><button>Visiteurs</button></a></td>
            
            
            
            </tr>
        
    </table>