<head> <meta charset="UTF-8">
 </head>    
    <div id="view-content">
        <p><h1>Liste des <b>locataires</h1></b>
    </div>
    <strong>Cliquer içi pour : <a href=<?php echo $this->url(array('controller' => 'locataires', 'action' => 'ajouter')); ?>> <button>Ajouter un locataire</button></a></strong><br/><br/>
    <table border="6">
        <tr>
            <td>Numero de locataire</td>
     
            <td> Nom locataire</td>
     
            <td> Prenom locataire</td>
     
            <td> Date naissance </td>
     
            <td> Tel</td>
     
            <td> RIB</td>
     
            <td> Banque</td>
     
            <td> Rue Banque</td>
     
            <td> Code ville Banque</td>
     
            <td>Tel banque</td>
                
     </tr> 
        

  
        <?php
        foreach ($this->leslocataires as $unlocataires) {
            if($unlocataires->NUMEROLOC!=0){?>
            <tr>
                <td><?php echo $unlocataires->NUMEROLOC;?></td></td>
     
                <td><?php echo $unlocataires->NOM_LOC;?></td></td>
     
                <td><?php echo $unlocataires->PRENOM_LOC;?></td></td>
                
                <td><?php echo $unlocataires->DATENAISS;?></td></td>
     
                <td><?php echo $unlocataires->TEL_LOC;?></td></td>
     
                <td><?php echo $unlocataires->R_I_B;?></td></td>
     
                <td><?php echo $unlocataires->BANQUE;?></td></td>
     
                <td><?php echo $unlocataires->RUE_BANQUE;?></td></td>
     
                <td><?php echo $unlocataires->CODEVILLE_BANQUE;?></td></td>
     
                <td><?php echo $unlocataires->TEL_BANQUE;?></td></td>
     
                <td><a href="<?php echo $this->url(array('controller' => 'locataires' , 'action'=>'modifier' ,  'NUMEROLOC' =>$unlocataires->NUMEROLOC)); ?> "> <button> Modifier </button></a></td>
                <td><a href="<?php echo $this->url(array('controller' => 'locataires' , 'action'=>'supprimer' , 'NUMEROLOC' =>$unlocataires->NUMEROLOC)); ?> "> <button> Supprimer </button></a></td>
                
     
            </tr>
            <?php
            }
        }
        ?>

    </table>
    
</html>