<a href="<?php echo $this->url(array('controller' => 'visiter', 'action' => 'index')); ?>">Retour</a>  

<div id="view-content">
    
</div>
<div id="form" style="width:350px;">
    <fieldset>
        <legend style="color:blue;font-weight:bold;">Gérer les visites</legend>
        <?php
        echo $this->form;
        ?>
    </fieldset>
</div>
<br/>
<strong>L'année doit être renseigné en AA/MM/JJ, exemple : 2008-02-01 </strong>