<br /><br />
<div id="view-content">
    <p>View script for controller <b>Visiter</b> and script/action name <b>ajouter</b></p>
</div>
<div id="form" style="width:350px;">
    <fieldset>
        <legend style="color:blue;font-weight:bold;">Gérer les visites</legend>
        <?php
        echo $this->form;
        ?>
    </fieldset>
</div>
<br/>
<strong>L'année doit être renseigné en AA/MM/JJ, exemple : 2008-02-01 </strong>