<a href="<?php echo $this->url(array('controller' => 'appartements', 'action' => 'index')); ?>">Retour</a>
<div id="view-content">
	<p>Ajouter un <b>Appartement</b></p>
        <p> Afin d'ajouter un Appartement sans locataire, veuillez selectionner <strong>le numero d'appartemen:" 0 "  </strong></P>
        
</div>

<?php
$this->title ="Ajouter un Appartement";
$this->headTitle($this->title);
echo $this->form;
?>