<p><h1><strong>Détails du propriétaire</strong></h1></p>


<table>
    <tr>
    <th> Numero du propriétaire</th>
    <th> NOM </th>
    <th> Prenom</th>
    <th> Adresse</th>
    <th> Code ville</th>
    <th> Telephone </th>
    </tr>
    <tr>
        <td><?php echo $this->proprio->NUMEROPROP;?></td>
        <td><?php echo $this->proprio->NOM;?></td>
        <td><?php echo $this->proprio->PRENOM;?></td>
        <td><?php echo $this->proprio->ADRESSE;?></td>
        <td><?php echo $this->proprio->CODE_VILLE;?></td>
        <td><?php echo $this->proprio->TEL;?></td>
        
    </tr>
</table>
