<p> Etes vous sur de vouloir supprimer l'appartement: 
    ' <?php echo $this->numappart; ?>'? 
</p>

<form action="<?php echo $this->url(array('controller' =>'appartements', 'action'=>'supprimer')); ?>" method="post">
    <div>
        <input type="hidden" name="NUMAPPART" value="<?php echo $this->numappart; ?>" />
        <input type="submit" name="supprimer" value="oui"/>
        <input type="submit" name="supprimer" value="non"/>
    </div>
</form>
